project:
  type: website
  output-dir: ../_site
  render:
    - plt-*.qmd

execute:
  echo: false
  eval: true

format:
  html:
    theme:
    - cosmo
    - brand
    toc: true
    toc-depth: 4
    css: assets/pega-report-overrides.css
    embed-resources: false
notebook-links: false